version: "3"

services:
  ui:
    image: provectuslabs/kafka-ui:latest
    restart: on-failure
    environment:
      KAFKA_CLUSTERS_0_NAME: kafka-ui
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: ${KAFKA_BOOTSTRAP_SERVER}
      KAFKA_CLUSTERS_0_PROPERTIES_SECURITY_PROTOCOL: ${KAFKA_SECURITY_PROTOCOL}
      KAFKA_CLUSTERS_0_PROPERTIES_SASL_MECHANISM: ${KAFKA_SASL_MECHANISM}
      KAFKA_CLUSTERS_0_PROPERTIES_SASL_JAAS_CONFIG: org.apache.kafka.common.security.scram.ScramLoginModule required username="${KAFKA_ADMIN_SASL_USERNAME}" password="${KAFKA_ADMIN_SASL_PASSWORD}";
    ports:
      - 8080:8080
      